In [25]:
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
mnist = fetch_openml('mnist_784', version=1)

In [2]:
print((np.array(mnist.data.loc[42]).reshape(28, 28) > 0).astype(int))

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 

In [3]:
print(mnist.keys())

dict_keys(['data', 'target', 'frame', 'categories', 'feature_names', 'target_names', 'DESCR', 'details', 'url'])


In [4]:
X = mnist.data
y = mnist.target

In [5]:
y = y.sort_values()

In [34]:
print(y.index)

Int64Index([34999, 56424, 56419, 16705, 56415, 56404, 56397, 56389, 56388,
            56429,
            ...
            13698, 33531, 13695, 13692, 58898, 13687, 42651, 58914, 13678,
            58529],
           dtype='int64', length=70000)


In [7]:
X.reindex(y.index)

pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  pixel9  \
34999     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56424     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56419     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
16705     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
56415     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
13687     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
42651     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58914     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
13678     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   
58529     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0     0.0   

       pixel10  ...  pixel775  pixel776  pixel777  pixel778  pixel779  \
34999      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56424      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56419      0.0  ...       0.0       0.0       0.0       0.0       0.0   
16705      0.0  ...       0.0       0.0       0.0       0.0       0.0   
56415      0.0  ...       0.0       0.0       0.0       0.0       0.0   
...        ...  ...       ...       ...       ...       ...       ...   
13687      0.0  ...       0.0       0.0       0.0       0.0       0.0   
42651      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58914      0.0  ...       0.0       0.0       0.0       0.0       0.0   
13678      0.0  ...       0.0       0.0       0.0       0.0       0.0   
58529      0.0  ...       0.0       0.0       0.0       0.0       0.0   

       pixel780  pixel781  pixel782  pixel783  pixel784  
34999       0.0       0.0       0.0       0.0       0.0  
56424       0.0       0.0       0.0       0.0       0.0  
56419       0.0       0.0       0.0       0.0       0.0  
16705       0.0       0.0       0.0       0.0       0.0  
56415       0.0       0.0       0.0       0.0       0.0  
...         ...       ...       ...       ...       ...  
13687       0.0       0.0       0.0       0.0       0.0  
42651       0.0       0.0       0.0       0.0       0.0  
58914       0.0       0.0       0.0       0.0       0.0  
13678       0.0       0.0       0.0       0.0       0.0  
58529       0.0       0.0       0.0       0.0       0.0  

[70000 rows x 784 columns]

In [8]:
X_train, X_test = X[:56000], X[56000:]
y_train, y_test = y[:56000], y[56000:]
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(56000, 784) (56000,)
(14000, 784) (14000,)


In [9]:
print(np.unique(y_train))

['0' '1' '2' '3' '4' '5' '6' '7']


In [10]:
print(np.unique(y_test))

['7' '8' '9']


In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [12]:
print(np.unique(y_train))

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


In [13]:
print(np.unique(y_test))

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9']


In [36]:
y_train_0 = (y_train == 0)
y_test_0 = (y_test == 0)
print(y_train_0)
print(np.unique(y_train_0))
print(len(y_train_0))

31880    False
20297    False
37782    False
16734    False
3737     False
         ...  
10775    False
9887     False
24112    False
7774     False
36975    False
Name: class, Length: 52500, dtype: bool
[False]
52500


In [32]:
sgd_clf = SGDClassifier()
sgd_clf.fit(X_train, y_train_0)
print(sgd_clf.predict([mnist.data.loc[0],mnist.data.loc[1]]))

[False False]


/opt/homebrew/Caskroom/miniforge/base/envs/ml/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but SGDClassifier was fitted with feature names
  warnings.warn(


In [28]:
score = cross_val_score(sgd_clf, X_train, y_train_0, cv=3, scoring="accuracy",n_jobs=-1)
print(score)

[0.78085714 0.83902857 0.81942857]
